#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

RIDER_EXE="$basedir/rider64.exe"
if ! [ -x "$RIDER_EXE" ]; then
  RIDER_EXE="$basedir/rider.bat"
fi
if ! [ -x "$RIDER_EXE" ]; then
  RIDER_EXE=rider
fi

(exec nohup "$RIDER_EXE" "$@" )  2>/dev/null &